[project]
name = "retromol"
version = "3.0.0"
description = "RetroMol is retrobiosynthetic analysis framework for modular natural products."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
authors = [{name="David Meijer", email="david.meijer@wur.nl"}]
keywords = ["natural-products", "biosynthesis", "retrobiosynthesis", "monomers"]

dependencies = [
    "rdkit==2025.9.1",
    "networkx==3.2.1",
    "biopython",
    "pyhmmer",
    "tqdm",
    "numpy",
    "scikit-learn<=1.8",
    "scipy",
    "pandas",
    "pyyaml",
    "ijson",
    "matplotlib",
    "joblib",
    "SQLAlchemy",
    "python-dotenv",
    "requests",
    "aiohttp",
    "asyncio",
    "duckdb",
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]

[project.urls]
Homepage = "https://github.com/moltools/retromol"
Repository = "https://github.com/moltools/retromol"
Issues = "https://github.com/moltools/retromol/issues"
Documentation = "https://github.com/moltools/retromol#readme"

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = ["pytest"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [
    "src/retromol",
    "src/retromol_cli",
    "src/retromol_alignment",
    "src/retromol_antismash",
    "src/retromol_database",
    "src/retromol_fingerprint",
    "src/retromol_synthesis",
    "src/retromol_paras",
]
include = [
    "src/retromol/data/mxn.yml",
    "src/retromol/data/rxn.yml",
    "src/retromol/data/pmp.yml",
    "src/retromol_antismash/data/AMP-binding_converted.hmm",
    "src/retromol_paras/data/*.hmm",
    "src/retromol_paras/data/*.txt",
    "src/retromol_paras/data/*.fasta",
    "src/retromol_paras/data/database_files/*",
]

[project.scripts]
retromol = "retromol_cli.cli:main"

# -------------------------
# Hatch env + scripts
# -------------------------
[tool.hatch.envs.dev]
features = ["dev"]
python = "3.10"

[tool.hatch.envs.dev.scripts]
test = "pytest -q"  # usage: hatch run dev:test
