# This Dockerfile builds API only
FROM python:3.9 

WORKDIR /app 
COPY ./src/server/ ./
RUN pip install -r ./requirements.txt 
ENV FLASK_ENV production 

EXPOSE 4004

WORKDIR /app

CMD ["sh", "-c", "gunicorn -b :4004 --timeout 120 api:app"]